[build]
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"
  
  # Build command for CI/CD
  command = "npm ci && npm run build"
  
  # Node.js version for build environment
  environment = { NODE_VERSION = "18" }

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets with MIME type fixes
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/javascript; charset=utf-8"

# MIME type fixes for all JavaScript files
[[headers]]
  for = "/**/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

[[headers]]
  for = "/**/*.mjs"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"

# Specific rules for Vite build outputs
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"
